utils::globalVariables(c(".", ":=",  "..betaMetrics", "..cols", "..colsBL", "..colsScen", "..id.vars", "..idCol",
                         "..keepCols", "..measure.vars", "..origDataVars", "Ancestors", "Axis1", "Axis2", "BL_C",
                         "BL_L", "BL_LD", "BL_Q", "BL_S", "BL_SDnormGen", "BL_SDnormVul", "BL_max.TL", "BL_mean.TL",
                         "BL_propB", "BL_propI", "BL_propOmn", "BL_propT", "BL_sd.TL", "C", "CCscen", "CS1", "CS2",
                         "Descendants", "L", "LD", "N", "PAGENAME", "PIX.HAB", "PK_UID", "Pext",
                         "Q", "Robust", "S", "SDM_stat", "SDMstat", "SDnormGen", "SDnormVul", "SPP", "Scen", "absDeltaC",
                         "code", "corrFile", "deltaC", "deltaL",
                         "deltaLD", "deltaQ", "deltaS", "deltaSDnormGen", "deltaSDnormVul", "deltamax.TL",
                         "deltamean.TL", "deltapropB", "deltapropI", "deltapropOmn", "deltapropT", "deltasd.TL",
                         "folder", "i", "invRobust", "lakes", "mask10k", "mask10kID",
                         "max.TL", "mean.TL", "mu", "multicore", "multisession", "nu",
                         "origFile", "phangorn", "predinvRobust", "propB", "propI", "propOmn", "propT",
                         "res", "sampID", "scen", "sd.TL",
                         "sppdist.dir", "tau", "trainData", "var", "x", "y"))
